## This GitHub Action automatically merges changes from the 'main' branch into the 'devel' branch
## whenever a push occurs on 'main'. It uses the devmasx/merge-branch action to perform the merge
## and sets a commit message. This keeps 'devel' up-to-date with the latest code from 'main'.
name: AutoMergeMainOnDevel

on:
  push:
    branches:
      - 'main'

jobs:
  auto_merge:
    if: github.repository == 'cnr-isti-vclab/vcglib'
    name: Automatic Merge Main On Devel
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Merge main -> devel
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: devel
        message: "Automatic merge branch 'main' into 'devel'"
        github_token: ${{ github.token }}
